spring.application.name=leader

spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#
jobrunr.dashboard.enabled=true
#
#jobrunr.background-job-server.enabled=true
spring.threads.virtual.enabled=true