spring.application.name=worker
#
jobrunr.background-job-server.enabled=true
#
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost/mydatabase

spring.threads.virtual.enabled=true